### ISSUE TITLE
java issues

### ISSUE THREAD

**Issue by kolad85** [mhelwig/adwind-decryptor#1]
I have tried running the .jar file as per the instructions but keep getting the following error regardless of what I try:

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.ParseException
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 7 more

I have tried that both on Windows and Linux and it seems to be some java related issue for which I can't find the solution.

**Comment by biebsmalwareguy** [comment]
Try here:
https://github.com/biebsmalwareguy/AdWindDecryptor/blob/master/AdWindDecryptor.jar

I pulled the source, re-wrote and corrected a few things, and just used it to successfully decrypt a sample.

**Comment by kolad85** [comment]
Hi biebsmalwareguy,

Many thanks for the fix!
